import { describe, it, expect } from 'vitest'
import type {
  DbModule,
  DbLesson,
  DbContentBlock,
  DbQuizQuestion,
  DbVideoComposition,
  DbContentVersion,
  ContentStatus,
  ContentBlockType,
} from '../admin'

describe('Admin Types', () => {
  describe('ContentStatus', () => {
    it('should allow valid status values', () => {
      const validStatuses: ContentStatus[] = ['draft', 'published', 'archived']
      expect(validStatuses).toHaveLength(3)
    })
  })

  describe('ContentBlockType', () => {
    it('should include all content block types', () => {
      const blockTypes: ContentBlockType[] = [
        'text',
        'heading',
        'subheading',
        'equation',
        'video',
        'callout',
        'list',
        'image',
        'diagram',
        'worked-example',
        'practice-problem',
      ]
      expect(blockTypes).toHaveLength(11)
    })
  })

  describe('DbModule', () => {
    it('should have required properties', () => {
      const module: DbModule = {
        id: 'uuid-123',
        slug: 'test-module',
        title: 'Test Module',
        description: 'A test module',
        icon: '🚀',
        order_index: 0,
        status: 'draft',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        created_by: null,
      }

      expect(module.id).toBe('uuid-123')
      expect(module.slug).toBe('test-module')
      expect(module.title).toBe('Test Module')
      expect(module.status).toBe('draft')
    })
  })

  describe('DbLesson', () => {
    it('should have required properties', () => {
      const lesson: DbLesson = {
        id: 'lesson-uuid',
        module_id: 'module-uuid',
        slug: 'test-lesson',
        title: 'Test Lesson',
        description: 'A test lesson',
        order_index: 0,
        estimated_minutes: 10,
        is_quiz: false,
        status: 'published',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        created_by: null,
      }

      expect(lesson.id).toBe('lesson-uuid')
      expect(lesson.module_id).toBe('module-uuid')
      expect(lesson.is_quiz).toBe(false)
      expect(lesson.estimated_minutes).toBe(10)
    })
  })

  describe('DbContentBlock', () => {
    it('should support text blocks', () => {
      const textBlock: DbContentBlock = {
        id: 'block-1',
        lesson_id: 'lesson-1',
        type: 'text',
        content: 'This is a text block',
        items: null,
        steps: null,
        difficulty: null,
        reveal_mode: null,
        answer: null,
        hints: null,
        input_placeholder: null,
        video_composition_id: null,
        image_url: null,
        image_alt: null,
        order_index: 0,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      }

      expect(textBlock.type).toBe('text')
      expect(textBlock.content).toBe('This is a text block')
    })

    it('should support practice-problem blocks', () => {
      const practiceBlock: DbContentBlock = {
        id: 'block-2',
        lesson_id: 'lesson-1',
        type: 'practice-problem',
        content: 'Calculate the thrust',
        items: null,
        steps: null,
        difficulty: 'intermediate',
        reveal_mode: 'hints',
        answer: '300,000 N',
        hints: ['Use the thrust equation', 'F = ṁ × v'],
        input_placeholder: 'Enter your answer',
        video_composition_id: null,
        image_url: null,
        image_alt: null,
        order_index: 1,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      }

      expect(practiceBlock.type).toBe('practice-problem')
      expect(practiceBlock.difficulty).toBe('intermediate')
      expect(practiceBlock.hints).toHaveLength(2)
    })
  })

  describe('DbQuizQuestion', () => {
    it('should support multiple-choice questions', () => {
      const question: DbQuizQuestion = {
        id: 'q-1',
        lesson_id: 'lesson-1',
        question_text: 'What is thrust?',
        question_type: 'multiple-choice',
        options: ['Force', 'Energy', 'Mass', 'Velocity'],
        correct_answer: 'Force',
        explanation: 'Thrust is a force generated by rockets',
        hint: 'Think about what pushes the rocket',
        difficulty: 'recall',
        topic_tags: ['thrust', 'basics'],
        is_auto_graded: true,
        order_index: 0,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      }

      expect(question.question_type).toBe('multiple-choice')
      expect(question.options).toHaveLength(4)
      expect(question.is_auto_graded).toBe(true)
    })

    it('should support true-false questions', () => {
      const question: DbQuizQuestion = {
        id: 'q-2',
        lesson_id: 'lesson-1',
        question_text: 'Rockets can work in space.',
        question_type: 'true-false',
        options: ['True', 'False'],
        correct_answer: 'True',
        explanation: 'Rockets carry their own propellant and oxidizer',
        hint: null,
        difficulty: 'understanding',
        topic_tags: ['rockets', 'space'],
        is_auto_graded: true,
        order_index: 1,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      }

      expect(question.question_type).toBe('true-false')
      expect(question.options).toHaveLength(2)
    })
  })

  describe('DbVideoComposition', () => {
    it('should have required video properties', () => {
      const video: DbVideoComposition = {
        id: 'video-1',
        name: 'Thrust Animation',
        slug: 'thrust-animation',
        description: 'Animation showing thrust',
        code: 'export function ThrustAnimation() { return <div>Animation</div> }',
        width: 1280,
        height: 720,
        fps: 30,
        duration_frames: 300,
        status: 'published',
        thumbnail_url: null,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        created_by: null,
      }

      expect(video.width).toBe(1280)
      expect(video.height).toBe(720)
      expect(video.fps).toBe(30)
      expect(video.duration_frames).toBe(300)
    })
  })

  describe('DbContentVersion', () => {
    it('should track version history', () => {
      const version: DbContentVersion = {
        id: 'version-1',
        entity_type: 'module',
        entity_id: 'module-1',
        version_number: 1,
        data: { title: 'Old Title' },
        change_summary: 'Updated title',
        created_at: '2024-01-01T00:00:00Z',
        created_by: 'user-1',
      }

      expect(version.entity_type).toBe('module')
      expect(version.version_number).toBe(1)
      expect(version.data).toHaveProperty('title')
    })
  })
})
