import type { Achievement } from '@/types/achievements'

export const ACHIEVEMENTS: Achievement[] = [
  // Learning achievements (lesson milestones)
  {
    id: 'first-lesson',
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: '🚀',
    category: 'learning',
    requirement: { type: 'lessons_completed', count: 1 },
    points: 10,
  },
  {
    id: 'five-lessons',
    title: 'Getting Started',
    description: 'Complete 5 lessons',
    icon: '📚',
    category: 'learning',
    requirement: { type: 'lessons_completed', count: 5 },
    points: 25,
  },
  {
    id: 'ten-lessons',
    title: 'Dedicated Learner',
    description: 'Complete 10 lessons',
    icon: '🎓',
    category: 'learning',
    requirement: { type: 'lessons_completed', count: 10 },
    points: 50,
  },
  {
    id: 'twenty-lessons',
    title: 'Knowledge Seeker',
    description: 'Complete 20 lessons',
    icon: '🧠',
    category: 'learning',
    requirement: { type: 'lessons_completed', count: 20 },
    points: 100,
  },

  // Module completion achievements
  {
    id: 'first-module',
    title: 'Module Master',
    description: 'Complete your first module',
    icon: '🏆',
    category: 'mastery',
    requirement: { type: 'modules_completed', count: 1 },
    points: 50,
  },
  {
    id: 'three-modules',
    title: 'Triple Threat',
    description: 'Complete 3 modules',
    icon: '⭐',
    category: 'mastery',
    requirement: { type: 'modules_completed', count: 3 },
    points: 150,
  },
  {
    id: 'all-modules',
    title: 'Rocket Scientist',
    description: 'Complete all modules',
    icon: '🎖️',
    category: 'mastery',
    requirement: { type: 'modules_completed', count: 6 },
    points: 500,
  },

  // Quiz achievements
  {
    id: 'first-quiz',
    title: 'Quiz Taker',
    description: 'Complete your first quiz',
    icon: '📝',
    category: 'learning',
    requirement: { type: 'quiz_count', count: 1 },
    points: 15,
  },
  {
    id: 'five-quizzes',
    title: 'Quiz Enthusiast',
    description: 'Complete 5 quizzes',
    icon: '✏️',
    category: 'learning',
    requirement: { type: 'quiz_count', count: 5 },
    points: 40,
  },
  {
    id: 'first-perfect',
    title: 'Perfect Score',
    description: 'Get a perfect score on a quiz',
    icon: '💯',
    category: 'mastery',
    requirement: { type: 'quiz_perfect', count: 1 },
    points: 30,
  },
  {
    id: 'five-perfects',
    title: 'Perfectionist',
    description: 'Get 5 perfect quiz scores',
    icon: '🌟',
    category: 'mastery',
    requirement: { type: 'quiz_perfect', count: 5 },
    points: 100,
  },

  // AI Tutor achievements
  {
    id: 'first-ai',
    title: 'Curious Mind',
    description: 'Ask the AI tutor a question',
    icon: '🤖',
    category: 'explorer',
    requirement: { type: 'ai_asked', count: 1 },
    points: 10,
  },
  {
    id: 'ten-ai',
    title: 'Inquisitive',
    description: 'Ask the AI tutor 10 questions',
    icon: '💭',
    category: 'explorer',
    requirement: { type: 'ai_asked', count: 10 },
    points: 50,
  },
  {
    id: 'fifty-ai',
    title: 'Deep Thinker',
    description: 'Ask the AI tutor 50 questions',
    icon: '🔬',
    category: 'explorer',
    requirement: { type: 'ai_asked', count: 50 },
    points: 150,
  },

  // Explorer achievements (visiting modules)
  {
    id: 'explorer-3',
    title: 'Explorer',
    description: 'Visit lessons in 3 different modules',
    icon: '🗺️',
    category: 'explorer',
    requirement: { type: 'modules_visited', count: 3 },
    points: 25,
  },
  {
    id: 'explorer-all',
    title: 'Full Explorer',
    description: 'Visit lessons in all modules',
    icon: '🌍',
    category: 'explorer',
    requirement: { type: 'modules_visited', count: 6 },
    points: 75,
  },

  // Simulator achievements - Flight
  {
    id: 'first-flight',
    title: 'Liftoff',
    description: 'Launch your first rocket in the flight simulator',
    icon: '🚀',
    category: 'simulator',
    requirement: { type: 'simulator_used', count: 1, simulatorType: 'flight' },
    points: 20,
  },
  {
    id: 'ten-flights',
    title: 'Frequent Flyer',
    description: 'Launch 10 rockets in the flight simulator',
    icon: '✈️',
    category: 'simulator',
    requirement: { type: 'simulator_used', count: 10, simulatorType: 'flight' },
    points: 75,
  },
  {
    id: 'altitude-10k',
    title: 'High Flyer',
    description: 'Reach 10,000m altitude in the flight simulator',
    icon: '🏔️',
    category: 'simulator',
    requirement: { type: 'simulator_milestone', count: 1, simulatorType: 'flight', milestoneValue: 10000 },
    points: 50,
  },
  {
    id: 'speed-343',
    title: 'Sound Barrier',
    description: 'Break the sound barrier (343 m/s) in the flight simulator',
    icon: '💨',
    category: 'simulator',
    requirement: { type: 'simulator_milestone', count: 1, simulatorType: 'flight', milestoneValue: 343 },
    points: 100,
  },

  // Simulator achievements - Orbit
  {
    id: 'first-orbit',
    title: 'Orbital Mechanics',
    description: 'Complete your first orbital transfer',
    icon: '🛰️',
    category: 'simulator',
    requirement: { type: 'simulator_used', count: 1, simulatorType: 'orbit' },
    points: 20,
  },
  {
    id: 'ten-orbits',
    title: 'Orbit Master',
    description: 'Complete 10 orbital transfers',
    icon: '🌙',
    category: 'simulator',
    requirement: { type: 'simulator_used', count: 10, simulatorType: 'orbit' },
    points: 75,
  },

  // Streak achievements
  {
    id: 'streak-3',
    title: 'Getting Consistent',
    description: 'Maintain a 3-day learning streak',
    icon: '🔥',
    category: 'streak',
    requirement: { type: 'streak', count: 3 },
    points: 20,
  },
  {
    id: 'streak-7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day learning streak',
    icon: '🔥',
    category: 'streak',
    requirement: { type: 'streak', count: 7 },
    points: 50,
  },
  {
    id: 'streak-30',
    title: 'Monthly Master',
    description: 'Maintain a 30-day learning streak',
    icon: '🔥',
    category: 'streak',
    requirement: { type: 'streak', count: 30 },
    points: 200,
  },
  {
    id: 'streak-100',
    title: 'Century Scholar',
    description: 'Maintain a 100-day learning streak',
    icon: '🔥',
    category: 'streak',
    requirement: { type: 'streak', count: 100 },
    points: 500,
  },

  // Flashcard achievements
  {
    id: 'flashcard-first-set',
    title: 'First Study Session',
    description: 'Complete your first flashcard set',
    icon: '📇',
    category: 'flashcards',
    requirement: { type: 'flashcard_sets_completed', count: 1 },
    points: 15,
  },
  {
    id: 'flashcard-ten-sets',
    title: 'Dedicated Reviewer',
    description: 'Complete 10 flashcard sets',
    icon: '📑',
    category: 'flashcards',
    requirement: { type: 'flashcard_sets_completed', count: 10 },
    points: 50,
  },
  {
    id: 'flashcard-streak-3',
    title: 'Review Streak',
    description: 'Maintain a 3-day flashcard review streak',
    icon: '🔄',
    category: 'flashcards',
    requirement: { type: 'flashcard_review_streak', count: 3 },
    points: 25,
  },
  {
    id: 'flashcard-streak-7',
    title: 'Weekly Reviewer',
    description: 'Maintain a 7-day flashcard review streak',
    icon: '📆',
    category: 'flashcards',
    requirement: { type: 'flashcard_review_streak', count: 7 },
    points: 75,
  },
  {
    id: 'flashcard-perfect',
    title: 'Perfect Memory',
    description: 'Get a perfect score on a flashcard set',
    icon: '🧠',
    category: 'flashcards',
    requirement: { type: 'flashcard_perfect_scores', count: 1 },
    points: 30,
  },
  {
    id: 'flashcard-master-25',
    title: 'Card Master',
    description: 'Master 25 flashcards',
    icon: '🃏',
    category: 'flashcards',
    requirement: { type: 'flashcard_cards_mastered', count: 25 },
    points: 50,
  },
  {
    id: 'flashcard-master-100',
    title: 'Memory Champion',
    description: 'Master 100 flashcards',
    icon: '🏅',
    category: 'flashcards',
    requirement: { type: 'flashcard_cards_mastered', count: 100 },
    points: 150,
  },

  // Additional learning achievements
  {
    id: 'lesson-streak-5',
    title: 'Learning Momentum',
    description: 'Complete lessons for 5 days in a row',
    icon: '📖',
    category: 'learning',
    requirement: { type: 'lesson_streak', count: 5 },
    points: 40,
  },
  {
    id: 'quiz-perfect-5',
    title: 'Quiz Ace',
    description: 'Get perfect scores on 5 different quizzes',
    icon: '🎯',
    category: 'mastery',
    requirement: { type: 'quiz_perfect', count: 5 },
    points: 100,
  },
  {
    id: 'practice-problems-10',
    title: 'Problem Solver',
    description: 'Complete 10 practice problems',
    icon: '🧩',
    category: 'learning',
    requirement: { type: 'practice_problems_completed', count: 10 },
    points: 30,
  },
]

export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id)
}

export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return ACHIEVEMENTS.filter(a => a.category === category)
}
