-- Sample Content for Content Management System
-- This seeds the database with sample modules, lessons, and content blocks

-- ============================================================================
-- SAMPLE MODULES
-- ============================================================================
INSERT INTO modules (id, slug, title, description, icon, order_index, status)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'how-rockets-fly', 'How Rockets Fly', 'Learn the fundamental physics of rocket propulsion, including Newton''s Third Law, thrust, and the basic mechanics of space flight.', '🚀', 0, 'published'),
  ('22222222-2222-2222-2222-222222222222', 'rocket-aerodynamics', 'Rocket Aerodynamics', 'Understand how air resistance affects rockets, and learn about drag, stability, and fin design for optimal flight performance.', '💨', 1, 'published'),
  ('33333333-3333-3333-3333-333333333333', 'orbital-mechanics', 'Orbital Mechanics', 'Explore the mathematics and physics of orbits, including Kepler''s laws, orbital maneuvers, and mission planning.', '🌍', 2, 'published'),
  ('44444444-4444-4444-4444-444444444444', 'propellants-and-engines', 'Propellants & Engines', 'Dive into the chemistry and engineering of rocket propulsion systems, from solid boosters to liquid-fueled engines.', '🔥', 3, 'draft')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  order_index = EXCLUDED.order_index,
  status = EXCLUDED.status;

-- ============================================================================
-- SAMPLE LESSONS
-- ============================================================================

-- How Rockets Fly lessons
INSERT INTO lessons (id, module_id, slug, title, description, order_index, estimated_minutes, is_quiz, status)
VALUES
  ('aaaa1111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111', 'what-is-thrust', 'What is Thrust?', 'Learn how rockets generate the force that propels them into space.', 0, 8, false, 'published'),
  ('aaaa2222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', 'newtons-third-law', 'Newton''s Third Law', 'Discover how action and reaction forces make rocket propulsion possible.', 1, 10, false, 'published'),
  ('aaaa3333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'module-1-quiz', 'Module 1 Quiz', 'Test your understanding of rocket propulsion basics.', 2, 5, true, 'published'),

  -- Rocket Aerodynamics lessons
  ('bbbb1111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 'understanding-drag', 'Understanding Drag', 'Learn how air resistance affects a rocket''s performance.', 0, 10, false, 'published'),
  ('bbbb2222-2222-2222-2222-222222222222', '22222222-2222-2222-2222-222222222222', 'fin-design', 'Fin Design & Stability', 'Explore how fins keep rockets flying straight.', 1, 12, false, 'published'),

  -- Orbital Mechanics lessons
  ('cccc1111-1111-1111-1111-111111111111', '33333333-3333-3333-3333-333333333333', 'keplers-laws', 'Kepler''s Laws of Planetary Motion', 'Understand the mathematical principles governing orbital motion.', 0, 15, false, 'published'),
  ('cccc2222-2222-2222-2222-222222222222', '33333333-3333-3333-3333-333333333333', 'delta-v', 'Delta-V and Orbital Maneuvers', 'Learn how to calculate the velocity changes needed for space missions.', 1, 15, false, 'published')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  estimated_minutes = EXCLUDED.estimated_minutes,
  is_quiz = EXCLUDED.is_quiz,
  status = EXCLUDED.status;

-- ============================================================================
-- SAMPLE CONTENT BLOCKS
-- ============================================================================

-- What is Thrust? content blocks
INSERT INTO content_blocks (id, lesson_id, type, content, order_index)
VALUES
  ('cb110001-0001-0001-0001-000000000001', 'aaaa1111-1111-1111-1111-111111111111', 'heading', 'Introduction to Thrust', 0),
  ('cb110002-0002-0002-0002-000000000002', 'aaaa1111-1111-1111-1111-111111111111', 'text', 'Thrust is the force that moves a rocket through the air and into space. It is generated by the rocket''s engines and is the result of expelling mass (propellant) at high velocity in one direction, which pushes the rocket in the opposite direction.', 1),
  ('cb110003-0003-0003-0003-000000000003', 'aaaa1111-1111-1111-1111-111111111111', 'callout', 'Key Concept: Thrust is measured in Newtons (N) or pounds-force (lbf). The Space Shuttle''s main engines produced about 1.8 million newtons of thrust each!', 2),
  ('cb110004-0004-0004-0004-000000000004', 'aaaa1111-1111-1111-1111-111111111111', 'heading', 'The Thrust Equation', 3),
  ('cb110005-0005-0005-0005-000000000005', 'aaaa1111-1111-1111-1111-111111111111', 'text', 'The thrust produced by a rocket engine can be calculated using the following equation:', 4),
  ('cb110006-0006-0006-0006-000000000006', 'aaaa1111-1111-1111-1111-111111111111', 'equation', 'F_{thrust} = \dot{m} \times v_{exhaust}', 5),
  ('cb110007-0007-0007-0007-000000000007', 'aaaa1111-1111-1111-1111-111111111111', 'text', 'Where ṁ (m-dot) is the mass flow rate of the propellant (kg/s) and v_exhaust is the velocity of the exhaust gases (m/s).', 6),

  -- Newton's Third Law content blocks
  ('cb220001-0001-0001-0001-000000000001', 'aaaa2222-2222-2222-2222-222222222222', 'heading', 'Newton''s Third Law of Motion', 0),
  ('cb220002-0002-0002-0002-000000000002', 'aaaa2222-2222-2222-2222-222222222222', 'text', 'Newton''s Third Law states: "For every action, there is an equal and opposite reaction." This fundamental principle of physics is the key to understanding how rockets work.', 1),
  ('cb220003-0003-0003-0003-000000000003', 'aaaa2222-2222-2222-2222-222222222222', 'callout', 'In a rocket, the "action" is the hot exhaust gases being expelled downward, and the "reaction" is the rocket being pushed upward with equal force.', 2),
  ('cb220004-0004-0004-0004-000000000004', 'aaaa2222-2222-2222-2222-222222222222', 'heading', 'How Rockets Use This Principle', 3),
  ('cb220005-0005-0005-0005-000000000005', 'aaaa2222-2222-2222-2222-222222222222', 'text', 'Unlike airplanes that push against air with propellers or jet engines, rockets carry their own propellant and oxidizer. This means they can work in the vacuum of space where there is no air to push against.', 4),
  ('cb220006-0006-0006-0006-000000000006', 'aaaa2222-2222-2222-2222-222222222222', 'list', 'Key Points:', 5),

  -- Understanding Drag content blocks
  ('cb330001-0001-0001-0001-000000000001', 'bbbb1111-1111-1111-1111-111111111111', 'heading', 'What is Drag?', 0),
  ('cb330002-0002-0002-0002-000000000002', 'bbbb1111-1111-1111-1111-111111111111', 'text', 'Drag is the aerodynamic force that opposes a rocket''s motion through the atmosphere. It acts in the opposite direction to the rocket''s velocity and increases with the square of the speed.', 1),
  ('cb330003-0003-0003-0003-000000000003', 'bbbb1111-1111-1111-1111-111111111111', 'equation', 'F_D = \frac{1}{2} \rho v^2 C_D A', 2),
  ('cb330004-0004-0004-0004-000000000004', 'bbbb1111-1111-1111-1111-111111111111', 'text', 'This is the drag equation, where ρ is air density, v is velocity, C_D is the drag coefficient, and A is the cross-sectional area.', 3)
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  content = EXCLUDED.content,
  order_index = EXCLUDED.order_index;

-- Update list items for Newton's Third Law
UPDATE content_blocks
SET items = '["Rockets work by conservation of momentum", "The exhaust velocity determines efficiency", "Higher mass flow rate means more thrust", "Rockets don''t need air to push against"]'::jsonb
WHERE id = 'cb220006-0006-0006-0006-000000000006';

-- ============================================================================
-- SAMPLE QUIZ QUESTIONS
-- ============================================================================
INSERT INTO quiz_questions (id, lesson_id, question_text, question_type, options, correct_answer, explanation, difficulty, order_index)
VALUES
  ('00110001-0001-0001-0001-000000000001', 'aaaa3333-3333-3333-3333-333333333333', 'What is the primary force that propels a rocket forward?', 'multiple-choice', '["Lift", "Thrust", "Drag", "Weight"]'::jsonb, 'Thrust', 'Thrust is the force generated by the rocket''s engines that propels it forward. It is produced by expelling mass (propellant) at high velocity.', 'recall', 0),
  ('00110002-0002-0002-0002-000000000002', 'aaaa3333-3333-3333-3333-333333333333', 'According to Newton''s Third Law, when a rocket expels gas downward, what happens to the rocket?', 'multiple-choice', '["It moves downward", "It moves upward with equal force", "It stays in place", "It spins"]'::jsonb, 'It moves upward with equal force', 'Newton''s Third Law states that for every action there is an equal and opposite reaction. When gases are expelled downward (action), the rocket is pushed upward (reaction).', 'understanding', 1),
  ('00110003-0003-0003-0003-000000000003', 'aaaa3333-3333-3333-3333-333333333333', 'Rockets can work in the vacuum of space.', 'true-false', '["True", "False"]'::jsonb, 'True', 'Unlike jets that need air to function, rockets carry their own propellant and oxidizer, allowing them to work in the vacuum of space.', 'understanding', 2),
  ('00110004-0004-0004-0004-000000000004', 'aaaa3333-3333-3333-3333-333333333333', 'If a rocket engine has a mass flow rate of 100 kg/s and exhaust velocity of 3000 m/s, what is the thrust?', 'multiple-choice', '["30,000 N", "300,000 N", "3,000,000 N", "3000 N"]'::jsonb, '300,000 N', 'Using the thrust equation F = ṁ × v_exhaust: F = 100 kg/s × 3000 m/s = 300,000 N', 'calculation', 3)
ON CONFLICT (id) DO UPDATE SET
  question_text = EXCLUDED.question_text,
  question_type = EXCLUDED.question_type,
  options = EXCLUDED.options,
  correct_answer = EXCLUDED.correct_answer,
  explanation = EXCLUDED.explanation,
  difficulty = EXCLUDED.difficulty,
  order_index = EXCLUDED.order_index;

-- ============================================================================
-- DONE
-- ============================================================================
SELECT 'Sample content seeded successfully!' as status;
