/**
 * @vitest-environment jsdom
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import React from 'react'
import { QuizSection } from '../QuizSection'
import type { QuizQuestion } from '@/types/course'

// Mock InlineLatex to just render text
vi.mock('../InlineLatex', () => ({
  InlineLatex: ({ children }: { children: React.ReactNode }) => <span>{children}</span>,
}))

const mockQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    questionText: 'What is the force that propels a rocket?',
    options: ['Thrust', 'Drag', 'Lift', 'Weight'],
    correctAnswer: 'Thrust',
    explanation: 'Thrust is the force generated by the rocket engine that propels it forward.',
  },
  {
    id: 'q2',
    questionText: 'What law describes action and reaction?',
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", 'Conservation of Energy'],
    correctAnswer: "Newton's Third Law",
    explanation: "Newton's Third Law states that for every action, there is an equal and opposite reaction.",
  },
]

describe('QuizSection', () => {
  const mockOnComplete = vi.fn()

  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('renders first question', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    expect(screen.getByText('What is the force that propels a rocket?')).toBeInTheDocument()
  })

  it('displays question counter', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    expect(screen.getByText('1 / 2')).toBeInTheDocument()
  })

  it('displays all answer options', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    expect(screen.getByText('Thrust')).toBeInTheDocument()
    expect(screen.getByText('Drag')).toBeInTheDocument()
    expect(screen.getByText('Lift')).toBeInTheDocument()
    expect(screen.getByText('Weight')).toBeInTheDocument()
  })

  it('disables Check Answer button when no answer selected', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    const checkButton = screen.getByText('Check Answer')
    expect(checkButton).toBeDisabled()
  })

  it('enables Check Answer button when answer selected', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    fireEvent.click(screen.getByText('Thrust'))

    const checkButton = screen.getByText('Check Answer')
    expect(checkButton).not.toBeDisabled()
  })

  it('shows correct feedback for correct answer', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))

    expect(screen.getByText('Correct!')).toBeInTheDocument()
  })

  it('shows incorrect feedback for wrong answer', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    fireEvent.click(screen.getByText('Drag'))
    fireEvent.click(screen.getByText('Check Answer'))

    expect(screen.getByText('Not quite.')).toBeInTheDocument()
  })

  it('shows explanation after answering', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))

    expect(screen.getByText(/Thrust is the force generated/)).toBeInTheDocument()
  })

  it('advances to next question', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    // Answer first question
    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))

    // Click Next Question
    fireEvent.click(screen.getByText('Next Question'))

    // Should show second question
    expect(screen.getByText("What law describes action and reaction?")).toBeInTheDocument()
    expect(screen.getByText('2 / 2')).toBeInTheDocument()
  })

  it('shows Finish Test button on last question', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    // Answer first question and advance
    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Next Question'))

    // Answer second question
    fireEvent.click(screen.getByText("Newton's Third Law"))
    fireEvent.click(screen.getByText('Check Answer'))

    // Should show Finish Test
    expect(screen.getByText('Finish Test')).toBeInTheDocument()
  })

  it('calls onComplete when quiz finished', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    // Answer first question correctly
    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Next Question'))

    // Answer second question correctly
    fireEvent.click(screen.getByText("Newton's Third Law"))
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Finish Test'))

    // onComplete should be called with score and total
    expect(mockOnComplete).toHaveBeenCalledTimes(1)
    expect(mockOnComplete).toHaveBeenCalledWith(expect.any(Number), 2)
  })

  it('shows completion screen after finishing', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    // Complete the quiz
    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Next Question'))

    fireEvent.click(screen.getByText("Newton's Third Law"))
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Finish Test'))

    expect(screen.getByText('Test Complete!')).toBeInTheDocument()
  })

  it('shows sign in prompt when not logged in', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={false}
      />
    )

    expect(screen.getByText('Sign in to save your test progress')).toBeInTheDocument()
  })

  it('does not show sign in prompt when logged in', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    expect(screen.queryByText('Sign in to save your test progress')).not.toBeInTheDocument()
  })

  it('disables answer selection after submitting', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    fireEvent.click(screen.getByText('Thrust'))
    fireEvent.click(screen.getByText('Check Answer'))

    // Options should be disabled (clicking should not change selection)
    const dragOption = screen.getByText('Drag').closest('button')
    expect(dragOption).toBeDisabled()
  })

  it('displays result with score', () => {
    render(
      <QuizSection
        questions={mockQuestions}
        onComplete={mockOnComplete}
        isLoggedIn={true}
      />
    )

    // Complete quiz with one correct, one incorrect
    fireEvent.click(screen.getByText('Drag')) // Wrong
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Next Question'))

    fireEvent.click(screen.getByText("Newton's Third Law")) // Correct
    fireEvent.click(screen.getByText('Check Answer'))
    fireEvent.click(screen.getByText('Finish Test'))

    expect(screen.getByText('Test Complete!')).toBeInTheDocument()
    // Should show score out of 2
    expect(screen.getByText(/out of 2/)).toBeInTheDocument()
  })
})
